#theme: jekyll-theme-cayman
#theme: minima
remote_theme: pages-themes/architect@v0.2.0
title: name.atomburg.com
show_downloads: false
description : "name.atomburg.com"
plugins:
- jekyll-remote-theme 
